# Generated by Django 2.1.7 on 2019-04-25 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='picker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picker', to=settings.AUTH_USER_MODEL, verbose_name='接单用户'),
        ),
        migrations.AddField(
            model_name='examine',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Tasks', verbose_name='所属任务'),
        ),
        migrations.AddField(
            model_name='classify',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Tasks', verbose_name='所属任务'),
        ),
    ]
