# Generated by Django 2.1.7 on 2019-05-03 15:58

import apps.index.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20190425_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='image',
            field=models.ImageField(blank=True, default='image/1508679309367.jpg', null=True, upload_to=apps.index.models.upload_directory_path, verbose_name='任务描述图片'),
        ),
    ]
